# This workflow is used by the `using-reuse.yml` & this will never execute alone.
name: Reusable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: The name of the deployable artifact files
                required: false
                default: dist
                type: string
        outputs:
            result: 
              description: The result of deployment op
              value: ${{ jobs.deploy.outputs.outcome }}
        # secrets:
        #     some-secret:
        #         required: false

jobs:
    deploy:
        outputs:
          outcome: ${{ steps.id_here.outputs.step-result }}
        runs-on: ubuntu-latest
        steps: 
            - name: Get Code
              uses: actions/download-artifact@v3
              with: 
                name: ${{ inputs.artifact-name }}
            - name: List files
              run: ls
            - name: Output information
              run: echo "Deploy and uploading"
            - name: Set output result
              id: id_here
              run: echo "step-result=success" >> $GITHUB_OUTPUT
